package StringApp;


/**
* StringApp/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOp.idl
* Tuesday, 21 April, 2026 11:19:17 PM IST
*/

public interface StringOperationOperations 
{
  String process (String input);
} // interface StringOperationOperations
