package StringApp;


/**
* StringApp/StringOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOp.idl
* Tuesday, 21 April, 2026 7:05:00 PM IST
*/

public interface StringOperation extends StringOperationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperation
