package StringApp;

/**
* StringApp/StringOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOp.idl
* Tuesday, 21 April, 2026 7:05:00 PM IST
*/

public final class StringOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public StringApp.StringOperation value = null;

  public StringOperationHolder ()
  {
  }

  public StringOperationHolder (StringApp.StringOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringApp.StringOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringApp.StringOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringApp.StringOperationHelper.type ();
  }

}
